import { IAwAppDetails } from '../../../../utils';

export const mockAppDetails: IAwAppDetails = {
  ApplicationName: 'appName',
  BundleId: 'com.lego.corp.bundleId',
  AppVersion: '0.0.1',
  ActualFileVersion: '0.0.1',
  AppType: 'appType',
  Status: 'Active',
  Platform: 2,
  SupportedModels: { Model: [] },
  AssignmentStatus: 'assStatus',
  ApplicationSize: '10.5mb',
  CategoryList: { Category: [] },
  SmartGroups: [{ Id: 1, Name: 'AD - adGroupName' }],
  IsReimbursable: false,
  ApplicationSource: 1,
  LocationGroupId: 2,
  RootLocationGroupName: 'rootLocationGroupName',
  LargeIconUri: 'largeIconUri',
  MediumIconUri: 'mediumIconUri',
  SmallIconUri: 'smallIconUri',
  PushMode: 1,
  AppRank: 1,
  AssignedDeviceCount: 1,
  InstalledDeviceCount: 1,
  NotInstalledDeviceCount: 1,
  AutoUpdateVersion: true,
  EnableProvisioning: true,
  IsDependencyFile: true,
  ContentGatewayId: 1,
  IconFileName: 'iconFileName',
  ApplicationFileName: 'appName',
  MetadataFileName: 'metaFileName',
  Id: { Value: 1 },
  Uuid: 'uuid',
};
