name: Build, Test and Publish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@lego'
      - run: npm install -g yarn
      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: yarn build
      - run: yarn test
        env:
          APPCENTER_API_TOKEN: appcenterApiToken
          APPCENTER_APP_NAME: appcenterAppName
          APPCENTER_OWNER_NAME: appcenterOwnerName
          BUNDLE_GIT__COM: bundleGitCom
          MATCH_PASSWORD: matchPassword
          GIT_USER: gitUser
          GIT_TOKEN: gitToken
          IOS_CERTIFICATES_GIT_URL: iosCertificatesGitUrl
          GH_TOKEN: ghAuthToken
          PROJECT_OR_WORKSPACE_PATH: projectOrWorkspacePath
          XCODE_SCHEME_NAME: xcodeSchemeName
      - run: echo @lego:registry=https://npm.pkg.github.com/ >> .npmrc
        if: github.ref == 'refs/heads/master'
      - run: yarn release:ci
        if: github.ref == 'refs/heads/master'
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
