name: Build, Test and Publish

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check Skip CI commits
        uses: veggiemonk/skip-commit@master
        env:
          COMMIT_FILTER: chore(release)
      - uses: actions/setup-node@v1
        with:
          version: 10
      - run: npm install -g yarn
      - run: npm config set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_TOKEN }}
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn release:ci
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
