name: Build & Test

on:
  pull_request:
    branches-ignore:
      - master
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check Skip CI commits
        uses: veggiemonk/skip-commit@master
        env:
          COMMIT_FILTER: skip-ci
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@lego'
      - run: npm install -g yarn
      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: yarn build
      # - run: yarn test
