name: Build, Test and Publish

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@lego'
      - run: npm install -g yarn
      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: yarn build
      - run: yarn test
      - run: echo @lego:registry=https://npm.pkg.github.com/ >> .npmrc
      - run: yarn release:ci
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
